<h1><?=$this->translate('error_occurred')?></h1>
<h2><?=isset($this->message)?$this->message:''?></h2>
<?php if(isset($this->display_exceptions) && $this->display_exceptions && isset($this->exception) && $this->exception instanceof \Exception){ ?>
<hr/>
<h2><?=$this->translate('additional_information')?> :</h2>
<h3><?=get_class($this->exception)?></h3>
<dl>
    <dt><?=$this->translate('file')?> :</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->exception->getFile()?>:<?=$this->exception->getLine()?></pre>
    </dd>
    <dt><?=$this->translate('message')?> :</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->exception->getMessage()?></pre>
    </dd>
    <dt><?=$this->translate('stack_trace')?> :</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->exception->getTraceAsString()?></pre>
    </dd>
</dl>
<?php if($oPreviousException = $this->exception->getPrevious()){ ?>
<hr/>
<h2><?=$this->translate('previous_exceptions')?> :</h2>
<ul class="unstyled">
<?php while($oPreviousException){ ?>
    <li>
        <h3><?=get_class($oPreviousException)?></h3>
        <dl>
            <dt><?=$this->translate('file')?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$oPreviousException->getFile()?>:<?=$oPreviousException->getLine()?></pre>
            </dd>
            <dt><?=$this->translate('message')?> :</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$oPreviousException->getMessage()?></pre>
            </dd>
            <dt><?=$this->translate('stack_trace')?> :</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$oPreviousException->getTraceAsString()?></pre>
            </dd>
        </dl>
    </li>
<?php
			$oPreviousException = $oPreviousException->getPrevious();
		}
?>
</ul>
<?php
		}
	}
?>